export const ANIMATION_CONSTANTS = {
  PAUSE_DURATION: 0.2,
  SUBSECTION_DURATION: 0.3,
  PROJECTS_SECTION_HEIGHT_MULTIPLIER: 0.8,
  CONTACT_SECTION_HEIGHT_MULTIPLIER: 0.4,
  FADE_OUT_THRESHOLD: 0.3,
  VIEWPORT_THRESHOLD: 0.6,
} as const
