export const ANIMATION_CONSTANTS = {
  PAUSE_DURATION: 0.1,
  SUBSECTION_DURATION: 0.15,
  PROJECTS_SECTION_HEIGHT_MULTIPLIER: 0.6,
  CONTACT_SECTION_HEIGHT_MULTIPLIER: 0.4,
  FADE_OUT_THRESHOLD: 0.5,
  VIEWPORT_THRESHOLD: 0.8,
} as const
